# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

# config/routes.yaml

# the "app_lucky_number" route name is not important yet
app_lucky_number:
    path: /lucky/number/
    controller: App\Controller\LuckyController::number
    
create_formation:
    path: /create/formation
    controller: App\Controller\LuckyController::createformation
    
create_experience:
    path: /create/experience
    controller: App\Controller\LuckyController::createexpericence
    
create_skill:
    path: /create/skill
    controller: App\Controller\LuckyController::createskill