# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

# config/routes.yaml

# the "app_lucky_number" route name is not important yet
app_lucky_number:
    path: /lucky/number/
    controller: App\Controller\LuckyController::number
    
create_formation:
    path: /create/formation
    controller: App\Controller\LuckyController::createformation
    
create_experience:
    path: /create/experience
    controller: App\Controller\LuckyController::createexpericence
    
create_skill:
    path: /create/skill
    controller: App\Controller\LuckyController::createskill
    
create_loisir:
    path: /loisir/create
    controller: App\Controller\LoisirController::create
    
valid_loisir:
    path: /loisir/valid
    controller: App\Controller\LoisirController::valid

    
edit_loisir:
    path: /loisir/edit/{id}
    controller: App\Controller\LoisirController::edit
    
create_experience:
    path: /experience/create
    controller: App\Controller\ExperienceController::create
    
valid_experience:
    path: /experience/valid
    controller: App\Controller\ExperienceController::valid

    
edit_experience:
    path: /experience/edit/{id}
    controller: App\Controller\ExperienceController::edit
    
create_formation:
    path: /formation/create
    controller: App\Controller\FormationController::create
    
valid_formation:
    path: /formation/valid
    controller: App\Controller\FormationController::valid

    
edit_formation:
    path: /formation/edit/{id}
    controller: App\Controller\FormationController::edit