# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

# config/routes.yaml

# the "app_lucky_number" route name is not important yet
app_lucky_number:
    path: /
    controller: App\Controller\LuckyController::number
    
create_formation:
    path: /create/formation
    controller: App\Controller\LuckyController::createformation
    
create_skill:
    path: /create/skill
    controller: App\Controller\LuckyController::createskill
    
create_loisir:
    path: /loisir/create
    controller: App\Controller\LoisirController::create
    
valid_loisir:
    path: /loisir/valid
    controller: App\Controller\LoisirController::valid

    
edit_loisir:
    path: /loisir/edit/{id}
    controller: App\Controller\LoisirController::edit

    
